# Generated by Django 4.1.3 on 2022-12-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
