# Generated by Django 4.1.3 on 2022-12-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_bookmarked_by_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='background_images/bg-image.jfif', upload_to='background_images'),
        ),
    ]
