# Generated by Django 4.1.3 on 2022-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_profile_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner_username',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='background_images/bg-image-1.jpg', upload_to='background_images'),
        ),
    ]
