# Generated by Django 4.1.3 on 2022-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='background_images/bg-image-4.jpg', upload_to='background_images'),
        ),
    ]
