# Generated by Django 4.1.3 on 2022-12-05 16:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_alter_profile_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarked_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Write something here'),
        ),
    ]
