# Generated by Django 4.1.3 on 2023-05-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_semantictag_custom_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='avatar',
            field=models.ImageField(default='space_images/default_space.jpg', upload_to='space_images'),
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.CharField(default='This is a Space!', max_length=100),
        ),
    ]
