# Generated by Django 4.1.3 on 2023-03-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='joined_at',
        ),
    ]
