# Generated by Django 4.1.3 on 2023-03-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_profile_joined_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified',
        ),
    ]
