# Generated by Django 4.1.3 on 2023-04-08 02:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_created_profile_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner_username',
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.user'),
        ),
    ]
