# Generated by Django 4.1.3 on 2023-04-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_post_owner_username_alter_post_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarked_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_of_bookmarks',
        ),
    ]
