# Generated by Django 4.1.3 on 2023-05-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_semantictag_post_semantic_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='semantic_tags',
        ),
        migrations.AddField(
            model_name='semantictag',
            name='custom_label',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='semantictag',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_tags', to='core.post'),
        ),
    ]
