# Generated by Django 4.1.3 on 2023-05-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_post_semantic_tags_semantictag_custom_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semantictag',
            name='custom_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='semantictag',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='semantictag',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='semantictag',
            name='wikidata_id',
            field=models.CharField(max_length=25),
        ),
    ]
