# Generated by Django 4.1.3 on 2023-05-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profile_background_image'),
        ('core', '0018_alter_semantictag_custom_label_and_more'),
    ]

    operations = [
    ]
