# Generated by Django 4.1.3 on 2023-05-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subscriber_space_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='label',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
