# Generated by Django 4.1.3 on 2023-05-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subscriber_space_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='background_images/bg-image-2.jpg', upload_to='background_images'),
        ),
    ]
