# Generated by Django 4.1.3 on 2023-05-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_bookmark_label_name_profile_available_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='background_images/bg-image-5.jpg', upload_to='background_images'),
        ),
    ]
