name: QA-Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']

    permissions:
      actions: read
      contents: read
      security-events: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Python
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Setup the environment
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      # Lint with Flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8

      # Generate the coverage report
      - name: Coverage Report
        run: |
          pip install coverage
          cd SWE574
          coverage report

#      # Run a CodeQL Analysis
#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v2
#        with:
#          languages: [ 'python' ]
#          # Override the default behavior so that the action doesn't attempt
#          # to auto-install Python dependencies
#          setup-python-dependencies: false
#
#      - name: Autobuild
#        uses: github/codeql-action/autobuild@v2
#
#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v2
#        with:
#          # Optional. Specify a category to distinguish between multiple analyses
#          # for the same tool and ref. If you don't use `category` in your workflow,
#          # GitHub will generate a default category name for you
#          category: "django"
